// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/tags/proto/tag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_internal_tags_proto_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tags_proto_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_internal_tags_proto_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetTagByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         int32                  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagByIdRequest) Reset() {
	*x = GetTagByIdRequest{}
	mi := &file_internal_tags_proto_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagByIdRequest) ProtoMessage() {}

func (x *GetTagByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tags_proto_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTagByIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_tags_proto_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagByIdRequest) GetTagId() int32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type GetTagByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tag           *Tag                   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagByIdResponse) Reset() {
	*x = GetTagByIdResponse{}
	mi := &file_internal_tags_proto_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagByIdResponse) ProtoMessage() {}

func (x *GetTagByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tags_proto_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTagByIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_tags_proto_tag_proto_rawDescGZIP(), []int{2}
}

func (x *GetTagByIdResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetTagByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTagByIdResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

var File_internal_tags_proto_tag_proto protoreflect.FileDescriptor

const file_internal_tags_proto_tag_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/tags/proto/tag.proto\x12\x02pb\"=\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"*\n" +
	"\x11GetTagByIdRequest\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\x05R\x05tagId\"a\n" +
	"\x12GetTagByIdResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x03tag\x18\x03 \x01(\v2\a.pb.TagR\x03tag2I\n" +
	"\n" +
	"TagService\x12;\n" +
	"\n" +
	"GetTagById\x12\x15.pb.GetTagByIdRequest\x1a\x16.pb.GetTagByIdResponseB\x05Z\x03pb/b\x06proto3"

var (
	file_internal_tags_proto_tag_proto_rawDescOnce sync.Once
	file_internal_tags_proto_tag_proto_rawDescData []byte
)

func file_internal_tags_proto_tag_proto_rawDescGZIP() []byte {
	file_internal_tags_proto_tag_proto_rawDescOnce.Do(func() {
		file_internal_tags_proto_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tags_proto_tag_proto_rawDesc), len(file_internal_tags_proto_tag_proto_rawDesc)))
	})
	return file_internal_tags_proto_tag_proto_rawDescData
}

var file_internal_tags_proto_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_tags_proto_tag_proto_goTypes = []any{
	(*Tag)(nil),                // 0: pb.Tag
	(*GetTagByIdRequest)(nil),  // 1: pb.GetTagByIdRequest
	(*GetTagByIdResponse)(nil), // 2: pb.GetTagByIdResponse
}
var file_internal_tags_proto_tag_proto_depIdxs = []int32{
	0, // 0: pb.GetTagByIdResponse.tag:type_name -> pb.Tag
	1, // 1: pb.TagService.GetTagById:input_type -> pb.GetTagByIdRequest
	2, // 2: pb.TagService.GetTagById:output_type -> pb.GetTagByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_tags_proto_tag_proto_init() }
func file_internal_tags_proto_tag_proto_init() {
	if File_internal_tags_proto_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tags_proto_tag_proto_rawDesc), len(file_internal_tags_proto_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_tags_proto_tag_proto_goTypes,
		DependencyIndexes: file_internal_tags_proto_tag_proto_depIdxs,
		MessageInfos:      file_internal_tags_proto_tag_proto_msgTypes,
	}.Build()
	File_internal_tags_proto_tag_proto = out.File
	file_internal_tags_proto_tag_proto_goTypes = nil
	file_internal_tags_proto_tag_proto_depIdxs = nil
}
