// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/categories/proto/category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCategoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdRequest) Reset() {
	*x = GetCategoryByIdRequest{}
	mi := &file_internal_categories_proto_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdRequest) ProtoMessage() {}

func (x *GetCategoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_categories_proto_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_categories_proto_category_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoryByIdRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type GetCategoryByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Category      *Category              `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdResponse) Reset() {
	*x = GetCategoryByIdResponse{}
	mi := &file_internal_categories_proto_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdResponse) ProtoMessage() {}

func (x *GetCategoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_categories_proto_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_categories_proto_category_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoryByIdResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetCategoryByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCategoryByIdResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_categories_proto_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_categories_proto_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_categories_proto_category_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_internal_categories_proto_category_proto protoreflect.FileDescriptor

const file_internal_categories_proto_category_proto_rawDesc = "" +
	"\n" +
	"(internal/categories/proto/category.proto\x12\bcategory\"9\n" +
	"\x16GetCategoryByIdRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\"{\n" +
	"\x17GetCategoryByIdResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\bcategory\x18\x03 \x01(\v2\x12.category.CategoryR\bcategory\"d\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription2i\n" +
	"\x0fCategoryService\x12V\n" +
	"\x0fGetCategoryById\x12 .category.GetCategoryByIdRequest\x1a!.category.GetCategoryByIdResponseB\x05Z\x03pb/b\x06proto3"

var (
	file_internal_categories_proto_category_proto_rawDescOnce sync.Once
	file_internal_categories_proto_category_proto_rawDescData []byte
)

func file_internal_categories_proto_category_proto_rawDescGZIP() []byte {
	file_internal_categories_proto_category_proto_rawDescOnce.Do(func() {
		file_internal_categories_proto_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_categories_proto_category_proto_rawDesc), len(file_internal_categories_proto_category_proto_rawDesc)))
	})
	return file_internal_categories_proto_category_proto_rawDescData
}

var file_internal_categories_proto_category_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_categories_proto_category_proto_goTypes = []any{
	(*GetCategoryByIdRequest)(nil),  // 0: category.GetCategoryByIdRequest
	(*GetCategoryByIdResponse)(nil), // 1: category.GetCategoryByIdResponse
	(*Category)(nil),                // 2: category.Category
}
var file_internal_categories_proto_category_proto_depIdxs = []int32{
	2, // 0: category.GetCategoryByIdResponse.category:type_name -> category.Category
	0, // 1: category.CategoryService.GetCategoryById:input_type -> category.GetCategoryByIdRequest
	1, // 2: category.CategoryService.GetCategoryById:output_type -> category.GetCategoryByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_categories_proto_category_proto_init() }
func file_internal_categories_proto_category_proto_init() {
	if File_internal_categories_proto_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_categories_proto_category_proto_rawDesc), len(file_internal_categories_proto_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_categories_proto_category_proto_goTypes,
		DependencyIndexes: file_internal_categories_proto_category_proto_depIdxs,
		MessageInfos:      file_internal_categories_proto_category_proto_msgTypes,
	}.Build()
	File_internal_categories_proto_category_proto = out.File
	file_internal_categories_proto_category_proto_goTypes = nil
	file_internal_categories_proto_category_proto_depIdxs = nil
}
