// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: internal/article_tags/proto/article_tag.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleTagService_CreateArticleTags_FullMethodName = "/pb.ArticleTagService/CreateArticleTags"
)

// ArticleTagServiceClient is the client API for ArticleTagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleTagServiceClient interface {
	CreateArticleTags(ctx context.Context, in *CreateArticleTagsRequest, opts ...grpc.CallOption) (*CreateArticleTagsResponse, error)
}

type articleTagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleTagServiceClient(cc grpc.ClientConnInterface) ArticleTagServiceClient {
	return &articleTagServiceClient{cc}
}

func (c *articleTagServiceClient) CreateArticleTags(ctx context.Context, in *CreateArticleTagsRequest, opts ...grpc.CallOption) (*CreateArticleTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArticleTagsResponse)
	err := c.cc.Invoke(ctx, ArticleTagService_CreateArticleTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleTagServiceServer is the server API for ArticleTagService service.
// All implementations should embed UnimplementedArticleTagServiceServer
// for forward compatibility.
type ArticleTagServiceServer interface {
	CreateArticleTags(context.Context, *CreateArticleTagsRequest) (*CreateArticleTagsResponse, error)
}

// UnimplementedArticleTagServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleTagServiceServer struct{}

func (UnimplementedArticleTagServiceServer) CreateArticleTags(context.Context, *CreateArticleTagsRequest) (*CreateArticleTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArticleTags not implemented")
}
func (UnimplementedArticleTagServiceServer) testEmbeddedByValue() {}

// UnsafeArticleTagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleTagServiceServer will
// result in compilation errors.
type UnsafeArticleTagServiceServer interface {
	mustEmbedUnimplementedArticleTagServiceServer()
}

func RegisterArticleTagServiceServer(s grpc.ServiceRegistrar, srv ArticleTagServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleTagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleTagService_ServiceDesc, srv)
}

func _ArticleTagService_CreateArticleTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArticleTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleTagServiceServer).CreateArticleTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleTagService_CreateArticleTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleTagServiceServer).CreateArticleTags(ctx, req.(*CreateArticleTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleTagService_ServiceDesc is the grpc.ServiceDesc for ArticleTagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleTagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ArticleTagService",
	HandlerType: (*ArticleTagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArticleTags",
			Handler:    _ArticleTagService_CreateArticleTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/article_tags/proto/article_tag.proto",
}
