// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/article_tags/proto/article_tag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateArticleTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     int32                  `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	TagIds        []int32                `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleTagsRequest) Reset() {
	*x = CreateArticleTagsRequest{}
	mi := &file_internal_article_tags_proto_article_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleTagsRequest) ProtoMessage() {}

func (x *CreateArticleTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_article_tags_proto_article_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleTagsRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleTagsRequest) Descriptor() ([]byte, []int) {
	return file_internal_article_tags_proto_article_tag_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArticleTagsRequest) GetArticleId() int32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *CreateArticleTagsRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type CreateArticleTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleTagsResponse) Reset() {
	*x = CreateArticleTagsResponse{}
	mi := &file_internal_article_tags_proto_article_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleTagsResponse) ProtoMessage() {}

func (x *CreateArticleTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_article_tags_proto_article_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleTagsResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleTagsResponse) Descriptor() ([]byte, []int) {
	return file_internal_article_tags_proto_article_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleTagsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateArticleTagsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_article_tags_proto_article_tag_proto protoreflect.FileDescriptor

const file_internal_article_tags_proto_article_tag_proto_rawDesc = "" +
	"\n" +
	"-internal/article_tags/proto/article_tag.proto\x12\x02pb\"R\n" +
	"\x18CreateArticleTagsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\x05R\tarticleId\x12\x17\n" +
	"\atag_ids\x18\x02 \x03(\x05R\x06tagIds\"O\n" +
	"\x19CreateArticleTagsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2e\n" +
	"\x11ArticleTagService\x12P\n" +
	"\x11CreateArticleTags\x12\x1c.pb.CreateArticleTagsRequest\x1a\x1d.pb.CreateArticleTagsResponseB\x05Z\x03pb/b\x06proto3"

var (
	file_internal_article_tags_proto_article_tag_proto_rawDescOnce sync.Once
	file_internal_article_tags_proto_article_tag_proto_rawDescData []byte
)

func file_internal_article_tags_proto_article_tag_proto_rawDescGZIP() []byte {
	file_internal_article_tags_proto_article_tag_proto_rawDescOnce.Do(func() {
		file_internal_article_tags_proto_article_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_article_tags_proto_article_tag_proto_rawDesc), len(file_internal_article_tags_proto_article_tag_proto_rawDesc)))
	})
	return file_internal_article_tags_proto_article_tag_proto_rawDescData
}

var file_internal_article_tags_proto_article_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_article_tags_proto_article_tag_proto_goTypes = []any{
	(*CreateArticleTagsRequest)(nil),  // 0: pb.CreateArticleTagsRequest
	(*CreateArticleTagsResponse)(nil), // 1: pb.CreateArticleTagsResponse
}
var file_internal_article_tags_proto_article_tag_proto_depIdxs = []int32{
	0, // 0: pb.ArticleTagService.CreateArticleTags:input_type -> pb.CreateArticleTagsRequest
	1, // 1: pb.ArticleTagService.CreateArticleTags:output_type -> pb.CreateArticleTagsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_article_tags_proto_article_tag_proto_init() }
func file_internal_article_tags_proto_article_tag_proto_init() {
	if File_internal_article_tags_proto_article_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_article_tags_proto_article_tag_proto_rawDesc), len(file_internal_article_tags_proto_article_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_article_tags_proto_article_tag_proto_goTypes,
		DependencyIndexes: file_internal_article_tags_proto_article_tag_proto_depIdxs,
		MessageInfos:      file_internal_article_tags_proto_article_tag_proto_msgTypes,
	}.Build()
	File_internal_article_tags_proto_article_tag_proto = out.File
	file_internal_article_tags_proto_article_tag_proto_goTypes = nil
	file_internal_article_tags_proto_article_tag_proto_depIdxs = nil
}
